name: ci
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  schedule:
    - cron: '20 4 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v3.5.3

      - name: 'Setup Go'
        uses: actions/setup-go@v4.0.1
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: 'Run tests'
        run: make test

      - name: 'Grab version'
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v') == true

      - name: 'Docker Hub login'
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/v') == true
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Publish to Docker Hub'
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/v') == true
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/honk:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/honk:${{ env.VERSION }}

      - name: 'Trigger deployment'
        if: startsWith(github.ref, 'refs/tags/v') == true
        run: >
          curl
          --fail
          --head
          --no-progress-meter
          --header "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}"
          "${{ secrets.WATCHTOWER_URL }}"
