name: publish
on:
  push:
    branches:
      - 'master'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v4.1.1

      - name: 'Setup Go'
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: 'Run tests'
        run: make test

      - name: 'Docker Hub login'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Publish to Docker Hub'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fonk:latest

      - name: 'Trigger deployment'
        run: >
          curl
          --fail
          --head
          --no-progress-meter
          --header "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}"
          "${{ secrets.WATCHTOWER_URL }}"
