name: test
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - 'master'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v4.1.1

      - name: 'Setup Go'
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: 'Run tests'
        run: make test
